# Generated by Django 6.0.5 on 2026-05-28 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="target_audience",
            field=models.CharField(
                choices=[("all", "All"), ("guests", "Guests"), ("staff", "Staff")],
                db_index=True,
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="commonareareservation",
            name="number_of_people",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="commonareareservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("maintenance", "Maintenance"),
                    ("inactive", "Inactive"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="number_of_guests",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("complaint", "Complaint"),
                    ("housekeeping", "Housekeeping"),
                    ("technical", "Technical"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                ],
                db_index=True,
                default="guest",
                max_length=10,
            ),
        ),
    ]
