# Generated by Django 6.0.5 on 2026-05-28 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_alter_announcement_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
