# Generated by Django 6.0.5 on 2026-05-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_roomtype_price_per_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("dining", "Dining"),
                            ("pool", "Pool"),
                            ("spa", "Spa & Wellness"),
                            ("fitness", "Fitness"),
                            ("entertainment", "Entertainment"),
                            ("business", "Business"),
                            ("family", "Family"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_free_for_guests", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offers/"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "common_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="hotel.commonarea",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_offers",
                "ordering": ["offer_type", "title"],
            },
        ),
    ]
