# Generated by Django 6.0.5 on 2026-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_hoteloffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteloffer",
            name="static_image",
            field=models.CharField(
                blank=True,
                help_text="Static image path like images/offers/rooftop_lounge.png",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="static_image",
            field=models.CharField(
                blank=True,
                help_text="Static image path like images/rooms/standard_city_room.png",
                max_length=255,
            ),
        ),
    ]
